# Generated by Django 6.0.2 on 2026-02-19 21:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHECKED_OUT', 'Checked Out'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='api.campus')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='api.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('location_text', models.CharField(blank=True, max_length=120)),
                ('accessible', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_monitor', models.BooleanField(default=False)),
                ('has_power', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='api.campus')),
            ],
            options={
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='api.equipmentitem')),
            ],
            options={
                'indexes': [models.Index(fields=['item', 'returned_at'], name='api_checkou_item_id_b50b85_idx'), models.Index(fields=['user', 'returned_at'], name='api_checkou_user_id_5e8c93_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='api.room')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'start_time', 'end_time'], name='api_reserva_room_id_2c56bb_idx'), models.Index(fields=['user', 'start_time'], name='api_reserva_user_id_235ac9_idx')],
            },
        ),
    ]
