# Generated by Django 6.0.2 on 2026-03-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus', 'verbose_name_plural': 'Campus'},
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Media', 'Media'), ('Electronics', 'Electronics'), ('Supplies', 'Supplies')], default='Supplies', max_length=30),
        ),
    ]
