# Generated by Django 6.0.2 on 2026-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_campus_options_equipmenttype_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttype',
            name='loan_period',
            field=models.CharField(default='24 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='location',
            field=models.CharField(default='Main Desk', max_length=100),
        ),
    ]
