# Generated by Django 6.0.2 on 2026-03-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_equipmenttype_loan_period_equipmenttype_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='category',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='loan_period',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
