# Generated by Django 6.0.2 on 2026-03-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_equipmenttype_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmenttype',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipmenttype',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='category',
            field=models.CharField(choices=[('Accessories', 'Accessories'), ('Media', 'Media'), ('Electronics', 'Electronics'), ('Supplies', 'Supplies')], default='Supplies', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
