# Generated by Django 6.0.2 on 2026-03-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_equipmenttype_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='loan_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='location_details',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='use_description',
            field=models.TextField(blank=True),
        ),
    ]
