# Generated by Django 6.0.2 on 2026-03-05 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_equipmentitem_loan_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
