# Generated by Django 6.0.2 on 2026-03-06 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipmentitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='location_details',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='use_description',
        ),
    ]
