# Generated by Django 6.0.2 on 2026-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_equipmentitem_loan_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='loan_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='name',
            field=models.CharField(default='Item', max_length=100),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='use',
            field=models.TextField(blank=True),
        ),
    ]
