# Generated by Django 6.0.2 on 2026-03-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_equipmentitem_available_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='available_quantity',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='total_quantity',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='use',
        ),
    ]
