# Generated by Django 6.0.2 on 2026-03-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_equipmentitem_available_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='loan_period',
            field=models.CharField(blank=True, help_text='e.g., 7 days, 24 hours.', max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the item.', max_length=120),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='use',
            field=models.TextField(blank=True, help_text='Describes how the item should be used.'),
        ),
    ]
