# Generated by Django 6.0.2 on 2026-03-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_equipmentitem_loan_period_equipmentitem_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='use',
        ),
    ]
