# Generated by Django 6.0.2 on 2026-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_equipmentitem_loan_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='loan_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='use',
            field=models.TextField(blank=True),
        ),
    ]
