# Generated by Django 6.0.2 on 2026-03-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_equipmentitem_description_equipmentitem_loan_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='name',
            field=models.CharField(default='Item', max_length=100),
        ),
    ]
