# Generated by Django 6.0.2 on 2026-03-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_equipmentitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='loan_period',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='use',
        ),
    ]
