# Generated by Django 6.0.2 on 2026-03-07 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_equipmentitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentitem',
            old_name='notes',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='asset_tag',
        ),
        migrations.RemoveField(
            model_name='equipmentitem',
            name='status',
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='loan_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='use',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.campus'),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmenttype'),
        ),
        migrations.CreateModel(
            name='EquipmentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_tag', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.equipmentitem')),
            ],
        ),
    ]
