# Generated by Django 6.0.2 on 2026-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_notes_equipmentitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
