# Generated by Django 6.0.2 on 2026-03-07 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_equipmentitem_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='api.equipmentasset'),
        ),
    ]
