# Generated by Django 6.0.2 on 2026-03-07 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_checkout_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.equipmentasset'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts', to='api.equipmentitem'),
        ),
    ]
