# Generated by Django 6.0.2 on 2026-03-07 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_checkout_assigned_asset_alter_checkout_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='assigned_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipmentasset'),
        ),
    ]
