# Generated by Django 6.0.2 on 2026-03-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_checkout_assigned_asset'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='checkout',
            name='api_checkou_item_id_b50b85_idx',
        ),
        migrations.RemoveIndex(
            model_name='checkout',
            name='api_checkou_user_id_5e8c93_idx',
        ),
    ]
