# Generated by Django 6.0.2 on 2026-03-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_checkout_api_checkou_item_id_b50b85_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='available_quantity',
        ),
    ]
