# Generated by Django 6.0.2 on 2026-03-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_equipmentitem_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentitem',
            name='campus',
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipmentitem',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
