# Generated by Django 6.0.2 on 2026-03-07 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_equipmentitem_campus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='equipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmenttype'),
        ),
    ]
