# Generated by Django 6.0.2 on 2026-04-06 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_waitlist_notification_deadline_waitlisthold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlisthold',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds_created_by_cancellation', to=settings.AUTH_USER_MODEL),
        ),
    ]
