# Generated by Django 6.0.2 on 2026-04-07 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_waitlisthold_cancelled_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='waitlist',
            name='room_start_time',
            field=models.DateTimeField(blank=True, help_text='The slot start time this user was trying to reserve. Used to compute their booking deadline.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('user', 'room')},
        ),
    ]
