# Generated by Django 6.0.2 on 2026-04-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_reservation_options_waitlist_room_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlist',
            name='room_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
