# Generated by Django 6.0.2 on 2026-04-21 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_waitlist_room_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
