# Generated by Django 6.0.2 on 2026-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_checkout_reminder_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_cancelled',
            field=models.BooleanField(default=True),
        ),
    ]
