# Generated by Django 6.0.2 on 2026-05-04 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_checkout_is_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='is_cancelled',
        ),
    ]
