# Generated by Django 6.0.2 on 2026-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_checkout_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
