"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!@9d3l%^!bsi1*a97c!zu$#ew1m+x10n4h@0u&84*yir(xv9%g"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'jazzmin', # added for jazzmin 
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "api",
    "django_apscheduler",
]

# new for django admin panel
JAZZMIN_SETTINGS = {
    # title in the browser tab and top bar
    "site_title": "LibraryCentral Admin",
    "site_header": "LibraryCentral Administration",
    "site_brand": "LibraryCentral",

    # welcome text on the login page
    "welcome_sign": "Welcome to LibraryCentral Administration",

    # copyright footer
    "copyright": "LibraryCentral",

    # top nav links (optional — shows quick links in the top bar)
    "topmenu_links": [
        {"name": "View Site", "url": "/", "new_window": False},
    ],

    # side nav icons — uses Font Awesome 5 free icon names
    "icons": {
        "auth":                     "fas fa-users-cog",
        "auth.user":                "fas fa-user",
        "auth.Group":               "fas fa-users",
        "api.Campus":               "fas fa-university",
        "api.Room":                 "fas fa-door-open",
        "api.Reservation":          "fas fa-calendar-check",
        "api.EquipmentItem":        "fas fa-box",
        "api.EquipmentType":        "fas fa-tags",
        "api.Checkout":             "fas fa-clipboard-list",
        "api.Waitlist":             "fas fa-hourglass-half",
        "api.WaitlistHold":         "fas fa-lock",
        "api.Notification":         "fas fa-bell",
    },

    # group models in the sidebar under custom headings
    "order_with_respect_to": [
        "auth",
        "api.Campus",
        "api.Room",
        "api.Reservation",
        "api.Waitlist",
        "api.WaitlistHold",
        "api.EquipmentType",
        "api.EquipmentItem",
        "api.EquipmentAsset",
        "api.Checkout",
        "api.Notification",
    ],

    # hide models from sidebar if you don't need them cluttering the nav
    "hide_models": [],

    # show model count in sidebar
    "show_sidebar": True,
    "navigation_expanded": True,

    # search bar in top nav — lets you search across all models
    "search_model": ["auth.user"],

    # user avatar in top nav
    "user_avatar": None,
}


# optional: customize the color theme (commented out for now)
# JAZZMIN_UI_TWEAKS = {
#     "navbar_small_text": False,
#     "footer_small_text": False,
#     "body_small_text": False,
#     "brand_small_text": False,

#     # color theme for the top bar and sidebar
#     # options: "primary","secondary","info","warning","danger","success","dark","light"
#     "brand_colour": "navbar-dark",
#     "accent": "accent-primary",
#     "navbar": "navbar-dark",
#     "no_navbar_border": True,
#     "navbar_fixed": True,

#     # side style
#     "sidebar": "sidebar-dark-primary",   # dark sidebar (matches the mockup I showed you)
#     "sidebar_nav_small_text": False,
#     "sidebar_disable_expand": False,
#     "sidebar_nav_child_indent": True,
#     "sidebar_nav_compact_style": False,
#     "sidebar_nav_flat_style": False,

#     # theme — pick one:
#     # "default", "cerulean", "cosmo", "flatly", "journal", "litera",
#     # "lumen", "lux", "materia", "minty", "pulse", "sandstone",
#     # "simplex", "sketchy", "slate", "solar", "spacelab", "superhero",
#     # "united", "yeti"
#     "theme": "flatly",       # clean, modern — closest to what I showed you
#     "dark_mode_theme": None,

#     "button_classes": {
#         "primary": "btn-primary",
#         "secondary": "btn-secondary",
#         "info": "btn-outline-info",
#         "warning": "btn-warning",
#         "danger": "btn-danger",
#         "success": "btn-success",
#     },
# }

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    

]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {
            "timeout": 20,  # wait up to 20s before raising locked error
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
ALLOWED_HOSTS = ["*"]
# CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_ALL_ORIGINS = True #changed to allow requsest from any origin (wasn't sure if react was running on a diferent port thandjango backend)

# Media files (uploaded images of equipment)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# DRF defaults:
# - Authenticate every API request using Microsoft Bearer tokens (sets request.user)
# - Require users to be logged in for all endpoints unless a view overrides with AllowAny
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https:\/\/.*\.app\.github\.dev$",
]
CSRF_TRUSTED_ORIGINS = [
    "https://*.app.github.dev",
    "https://localhost:8000",
    "https://127.0.0.1:8000",
]

# Codespaces uses an HTTPS reverse proxy in front of the Django server.
# Without these settings, Django may treat requests as insecure and reject
# admin logins with CSRF/Forbidden errors.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if os.getenv("CODESPACES") == "true":
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
# Add this import + settings right here (below CSRF_TRUSTED_ORIGINS)
from corsheaders.defaults import default_headers, default_methods

# Allow headers axios/JWT commonly send (preflight checks these)
CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
]

# Ensure OPTIONS + other methods are allowed for preflight
CORS_ALLOW_METHODS = list(default_methods)

# Optional: okay for dev; helps if you ever use cookies
CORS_ALLOW_CREDENTIALS = True
REST_FRAMEWORK = {
    # This tells DRF how to authenticate the token your login endpoint returns
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],

    # Default: all endpoints require login unless a view overrides with AllowAny
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

# before we didn't have any JWT settings defined, so Django used SimpleJWT defaults ( access token=5 mins, refresh token=1 day )
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=24),   # login pass expires in 24 hours (can change it, need to decide)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),

    "AUTH_HEADER_TYPES": ("Bearer",),
}


# NEW: Django email configuration
# In development, the console backend prints emails in the terminal.
# switch EMAIL_BACKEND to SMTP for real email sending LATERRRRRR
#https://docs.djangoproject.com/en/6.0/topics/email/?utm_

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@librarycentral.local")

# NEW: reminder windows in hours
# Room reminder = how many hours before reservation start we send the reminder
ROOM_REMINDER_HOURS = int(os.getenv("ROOM_REMINDER_HOURS", "2"))

# Equipment reminder = how many hours before equipment due date we send the reminder
EQUIPMENT_REMINDER_HOURS = int(os.getenv("EQUIPMENT_REMINDER_HOURS", "2"))

#optional SMS webhook configuration
# blank, SMS is skipped safely and email still works.
SMS_WEBHOOK_URL = os.getenv("SMS_WEBHOOK_URL", "")
SMS_WEBHOOK_TOKEN = os.getenv("SMS_WEBHOOK_TOKEN", "")